### ISSUE TITLE
Data sources acronyms

### ISSUE THREAD

**Issue by lucalamoni** [ices-tools-dev/online-advice#132]
The references to other systems should be spelt out with the acronym in brackets – Stock Information Database (SID); The first one is called “ICES Spatial Facility” and has no acronym.

@neil-ices-dk Should SID, SAG and Advice View also be prefixed with ICES?

**Comment by neil-ices-dk** [comment]
@lucalamoni i don't think so, the spatial facility is the only one i know that is specifically prefixed with 'ICES'
