### ISSUE TITLE
Use common Stock Information and Advice Headline functions across stock development, QoA & Catch Scenarios

### ISSUE THREAD

**Issue by Neilmagi** [ices-tools-dev/online-advice#133]
These functions do not differ apart from the id, so it should be possible to commonise them.

@lucalamoni is the information identical in all 3 tabs? And are the functions in the server identical?

**Comment by lucalamoni** [comment]
The function that creates the stock info and headline is the same, but the outputs' names in the server and ui need to be different from each other (at least when I tried to use the same names the app crashed)
