### ISSUE TITLE
Headline View issues

### ISSUE THREAD

**Issue by Neilmagi** [ices-tools-dev/online-advice#145]
- [x] 2021 bss.27.4bc7ad-h Headline Advice missing in app
- [x] 2021 GNS ple.27.7d Headline Advice doesn't display properly

**Comment by lucalamoni** [comment]
@Neilmagi I think we can close this issue down:
BSS is not in our list of stocks for launch
PLE headline title is now showing correctly, Laura worked on it, but the link itself is not working and if you try to click on it you get a "not found" page. So as far as we are concerned for the app, it is ok.
