### ISSUE TITLE
Bugs to fix before launch

### ISSUE THREAD

**Issue by lucalamoni** [ices-tools-dev/online-advice#153]

**Comment by lucalamoni** [comment]
- [x] Baltic ecoregion, spr.27.22-32, 2021 -->  **Error in Recruitment plot** Error in check_aesthetics: Aesthetics must be either length 1 or the same as the data (1): ymin, ymax, x and y
  126: <Anonymous>
- [x] Norwegian Sea, reg.27.561214, 2021 and 2022 (but not other years), error in recruitment plot --> Error in check_aesthetics: Aesthetics must be either length 1 or the same as the data (1): x and y
- [x] Landings do not appear because the data is in the column "catches" and "landings" is all NAs (check with @sarahlmillar that copying the values from catches to landings is correct)
- [x] tur.27.4, 2019, TAC change column catch scen table
- [x] ple.27.7d, 2019 Quality of ass, and F_SSB_catches plot have F (ages NA), but SAG plot is OK
- [x] nop.27.3a4, 2019 problem with missed columns catch scen table
- [x] Ghl.27.1-2, 2019 error in catch scenarios because there is one advice view entry every 2years

@lucalamoni I believe tur.27.4 has the same problem as ghl.27.1-2. The function get_Advice_View_info() fails when there is no advice to return. I'm not sure we'll have a (good) fix prior to launch

- [x] investigate possible bug in catch scenario graph for cod.27.47d20 in Assessment year: 2018

**Comment by lucalamoni** [comment]
@Neilmagi @sarahlmillar re ghl.27.1-2, 2021, I just noticed that the headline advice in 2021 gives 2 separate advice for 2022 and 2023. In addition, it's giving us an error cause the advice view entries are not in consecutive years (the previous is in 2019). Should we take it off the list?

**Comment by Neilmagi** [comment]
Yeah we need to have a good think about what to do with these years and stocks where there is no assessment but where there is valid advice from a previous assessment. I don't think this is something we'll do prior to launch, so I'd agree to taking it off the list ( also tur.27.4)

**Comment by lucalamoni** [comment]
@Neilmagi I will copy here the stocks we need to have a look from above:

- [x] tur.27.4, 2019, TAC change column catch scen table
- [x] ple.27.7d, 2019 Quality of ass  plot have F (ages NA), but SAG plot is OK
- [x] nop.27.3a4, 2019 problem with missed columns catch scen table
- [x] dgs.27.nea, 2022 gives 2 different advice values for one advice entry + catch scen table with different columns is not displayed well (@sarahlmillar should I remove it?)
- [x] por.27.nea, 2022 (azores) Relative biomass plot not showed correctly + gives 2 different advice values for one advice entry (@sarahlmillar should I remove it?)
- [x] spr.27.3a4,2022 (north sea) No advice view entry (@sarahlmillar will publish this one)
- [x] sol.27.7e, 2022 (north sea) Fprojectedlandings not in catch scenario table
- [x] cod.21.1, 2019 (artic ocean) no historical catches in catch time series plot
- [x] ank.27.78abd, 2022 (north sea) catch time series Error in : $ operator is invalid for atomic vectors -- renderUI [D:\Profile\Documents\GitHub\online-advice\App/server.R#380]
- [x] her.27.irls, 2022 (celtic seas) the shaded recruitment year is not the last one, check x lim 
- [ ] cod.27.2.coastS, 2022 (norwegian sea) Biomass index plot not displaying correctly (https://ices-library.figshare.com/articles/report/Cod_Gadus_morhua_in_Subarea_2_between_62_N_and_67_N_Norwegian_Sea_southern_Norwegian_coastal_cod/21840822)
- [x] mac.27.nea,2022 (bay of biscay) in catch scen tab Warning: Error in check_pivot_spec: The `.name` column of `spec` must be unique.
- [x] sol.27.8ab, 2018 (bay of biscay) No F in catch scenario, probably is Fwanted
- [x] bsf.27.nea, 2018  qual of ass plots years should only be plotted as whole integers, no decimals
- [ ] scroll down option in quality of assessment tab (and potentially also in the map panel in landing page)
- [x] cod.27.24-32, 2020 (baltic) no values displayed in radial plot (her.27.20-24, 2020 too) missing values in catch scen table (check scale_catch_scenarios_for_radialPlot()
- [x] add shadedYears sagSettings also to landings plot
- [ ] ane.27.8 NA in SSB historical plot 2020, 2019, 2018
- [x] ank.27.78abd no headline advice (the advice view entry is unpublished, cause it's missing the doi, I asked Laura to fix it so that we can publish it)
- [x] had.27.5b, 2022 missing entry in advice view (I asked Laura if the can add it)

**Comment by sarahlmillar** [comment]
@lucalamoni  sorry for getting here a bit late. Agree - any stock where there are 2 advice for 2 different years in one advice sheet should not be included in this release. This is one of the main things we need the advice view team to fix up

**Comment by sarahlmillar** [comment]
@lucalamoni @Neilmagi years should only be plotted as whole integers, no decimals

**Comment by lucalamoni** [comment]
@sarahlmillar @Neilmagi re tur.27.4 I would like to keep it in. The code can now handle the case in which a stock does not have an advice view entry in the previous year. But we still get the catch scenario table and the SSB-F_catches plot.
