### ISSUE TITLE
Issues for ASD team

### ISSUE THREAD

**Issue by lucalamoni** [ices-tools-dev/online-advice#166]
- [x] #178 (only ICES people, create a button, @Milldaz sent the example stock)

- [x] #177 (allow to download XML)

- [x] #179

- [x] #180

- [x] #181

- [x] #182

- [x] Please notify Luca if the URL of the advice view is modified due to the db change of name

- [x] #183

- [x] If 'NoAdv' selected, not all 'required' fields still apply.

- [x] #184

**Comment by Milldaz** [comment]
Couldn't edit above. A couple other issues:
- If 'NoAdv' selected, not all 'required' fields still apply.
- block the publish button until the advice has been released officially
