### ISSUE TITLE
Prepare landing page for ICES website

### ISSUE THREAD

**Issue by lucalamoni** [ices-tools-dev/online-advice#168]
Template structure:
<img width="286" alt="Capture" src="https://user-images.githubusercontent.com/32708094/216053185-bbca3ad6-9379-4030-9284-e7670bee99fa.PNG">

**Comment by lucalamoni** [comment]
@neil-ices-dk here is the issue we can use to build up the materials for the landing page of the online advice

**Comment by neil-ices-dk** [comment]
first thing to settle, the landing page URL, will it simply be .../online-advice.aspx

**Comment by lucalamoni** [comment]
@neil-ices-dk we have a winner: AdviceXplorer
so I would imagine the url would look like  .../advicexplorer.aspx

**Comment by neil-ices-dk** [comment]
as it appears in the data report, was the Caps A negotiable ;)
![image](https://github.com/ices-tools-dev/online-advice/assets/23527005/d457ae9b-cfe5-4dc2-8d55-a21f4957f10d)

**Comment by neil-ices-dk** [comment]
Hi Luca - as emailed, Mark wants this version
![image](https://github.com/ices-tools-dev/online-advice/assets/23527005/110cac62-30aa-4879-844a-04fb0266e35c)

**Comment by neil-ices-dk** [comment]
@lucalamoni what location should the page be on ices.dk?

**Comment by lucalamoni** [comment]
@neil-ices-dk, following what was said during the meeting, the group suggested having a link to the page on the right menu of the latest advice page
<img width="668" alt="Screenshot 2023-06-01 122815" src="https://github.com/ices-tools-dev/online-advice/assets/32708094/263db78a-2ff2-4f39-bb4b-ceefd340cf70">

and on the general advice page 
![image](https://github.com/ices-tools-dev/online-advice/assets/32708094/50d74e6b-6bcb-4b01-baa7-deaa24a5a1dd)

**Comment by neil-ices-dk** [comment]
thanks Luca, these are just links though - so not really defining the page. I will go with a page under 
https://www.ices.dk/advice/Pages/xxxx.aspx which can then be linked from wherever :)

**Comment by lucalamoni** [comment]
> Hi Luca - as emailed, Mark wants this version ![image](https://user-images.githubusercontent.com/23527005/242534297-110cac62-30aa-4879-844a-04fb0266e35c.png)

I like this, did communications have a look at it as well? I need to test if I can embed it in the navbar, in terms of colors. During the meeting, I also showed the new color palette of the app, that we developed with the graphic designer. 
It will probably look more like this 
![MicrosoftTeams-image (1)](https://github.com/ices-tools-dev/online-advice/assets/32708094/88ec1716-6945-4c24-9b22-ee0bac3049a0)
or this
![MicrosoftTeams-image (2)](https://github.com/ices-tools-dev/online-advice/assets/32708094/8d3ac371-b9db-4206-9bfb-c69b33e07228)

**Comment by lucalamoni** [comment]
> thanks Luca, these are just links though - so not really defining the page. I will go with a page under https://www.ices.dk/advice/Pages/xxxx.aspx which can then be linked from wherever :)

yes, sorry for the confusion. Sounds good

**Comment by neil-ices-dk** [comment]
> > Hi Luca - as emailed, Mark wants this version ![image](https://user-images.githubusercontent.com/23527005/242534297-110cac62-30aa-4879-844a-04fb0266e35c.png)
> 
> I like this, did communications have a look at it as well? I need to test if I can embed it in the navbar, in terms of colors. During the meeting, I also showed the new color palette of the app, that we developed with the graphic designer. It will probably look more like this ![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/32708094/242571667-88ec1716-6945-4c24-9b22-ee0bac3049a0.png) or this ![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/32708094/242571870-8d3ac371-b9db-4206-9bfb-c69b33e07228.png)

Comms haven't had a look at this yet, will you take this forward with them?

**Comment by lucalamoni** [comment]
yes, if we make any modifications we will pass them by you and Mark

**Comment by lucalamoni** [comment]
![adviceXplorer logo_color](https://github.com/ices-tools-dev/online-advice/assets/32708094/aac4d17a-6943-44d6-a0e5-1c5856fa5681)
![adviceXplorer logo_negative](https://github.com/ices-tools-dev/online-advice/assets/32708094/b88c307d-1f6a-437f-8d45-263fc5d0d779)
 Hi @neil-ices-dk, here are the two final logos that Maria worked on if you need them on the landing page. The color one will be in the adviceXplorer on top of the map 

![image](https://github.com/ices-tools-dev/online-advice/assets/32708094/b76512f1-a060-4bf0-b77d-50627c724f17)

I will give you the text for the page asap.

**Comment by lucalamoni** [comment]
the white space below the color logo is the negative version of logo, with a white background is invisible :)

**Comment by lucalamoni** [comment]
[adviceXplorer_landing_page_content_TM_MDC_LL.docx](https://github.com/ices-tools-dev/online-advice/files/11746368/adviceXplorer_landing_page_content_TM_MDC_LL.docx)
Hi @neil-ices-dk, here is the edited text for the landing page using Terhi and Marc's suggestions. The metadata record is almost ready for publishing and Periklis is just waiting for me to deploy the app at the final URL. I'm also working on the disclaimer.

**Comment by lucalamoni** [comment]
https://github.com/ices-tools-prod/disclaimers/blob/master/Disclaimer_adviceXplorer.txt

**Comment by neil-ices-dk** [comment]
@lucalamoni and so it begins
https://www.ices.dk/advice/Pages/adviceXplorer.aspx 

We're not able to place the logo graphic in the title (as you have it in the Word file), it can only go in the body or right hand side, so i have for the moment put it in the image box. 
 
Unlike the data section, advice don't follow the same left hand navigation on each page; this means there is potential to create a navigation that equates to the top menu tabs in the shinyapp; have a think about that, otherwise we can leave it blank and change the layout to make the page wider

![image](https://github.com/ices-tools-dev/online-advice/assets/23527005/fc81f499-55d2-4ef3-ae67-6f1025f234f0)

**Comment by lucalamoni** [comment]
Hi @neil-ices-dk, looking good!
I'll have a think about the menu. In the end, you decided to avoid the app iframe in the landing page?

**Comment by lucalamoni** [comment]
https://ices-taf.shinyapps.io/advicexplorer/
I deployed the app on the new URL

**Comment by lucalamoni** [comment]
Periklis will publish the metadata record soon and I finalized the Disclaimer, which now is zipped together with csv files when the user downloads the data

**Comment by neil-ices-dk** [comment]
> Hi @neil-ices-dk, looking good! I'll have a think about the menu. In the end, you decided to avoid the app iframe in the landing page?

it's just for this ICES app we need a proper landing page with context and links regardless of whether we have a page with the embedded app. I think that because the app is ICES, and is branded as such, it is not necessary to have the embedded app.

**Comment by neil-ices-dk** [comment]
so all we need are 'call to action' buttons on the right hand side

**Comment by lucalamoni** [comment]
I'm not 100% sure what needs to go in the "call to actions" buttons but on top of my head I would put:
- link to the adviceXplorer
- link to the github repo
- link to the metadata record
- link to the ASD

**Comment by neil-ices-dk** [comment]
> * link to the github repo
> 
> * link to the metadata record

do you have these links @lucalamoni

**Comment by lucalamoni** [comment]
- https://github.com/ices-tools-dev/online-advice.git
- @PeriklisICES could you add here the link to the metadata record?

**Comment by neil-ices-dk** [comment]
Github link added;
Celine is asking where this page will be linked from, so please check with Lotte where on the advice site it will sit (linkwise)

**Comment by PeriklisICES** [comment]
The link to the metadata is this:
https://gis.ices.dk/geonetwork/srv/eng/catalog.search#/metadata/8046f4e2-f62f-4c0b-b970-70d29602e710

**Comment by neil-ices-dk** [comment]
thanks @PeriklisICES now implemented.

I would say the page is ready
![image](https://github.com/ices-tools-dev/online-advice/assets/23527005/803adae7-1702-424f-8150-22db688ae5ef)

**Comment by lucalamoni** [comment]
It looks great :)
Thank you @neil-ices-dk and thank you @PeriklisICES !

**Comment by lucalamoni** [comment]
@neil-ices-dk do we need to update anything in google analytics?

**Comment by neil-ices-dk** [comment]
The standard SharePoint landing page will be fine, but we will need to do something for the shinyapp url as that has changed.

**Comment by lucalamoni** [comment]
the google tag

<script async src="https://www.googletagmanager.com/gtag/js?id=G-HP6S381CKY"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'G-HP6S381CKY');
</script>
is already in the app, so I guess is just a matter of finding the page on google analytics

**Comment by neil-ices-dk** [comment]
have made a link from the 'assessment tools' in the data area (below). assume you will make the links from Advice with Celine/Michala?
![image](https://github.com/ices-tools-dev/online-advice/assets/23527005/ee3eb23a-7398-4b42-9a7e-cbd79c77d67b)

**Comment by lucalamoni** [comment]
thank you, yes, Celine should take care of the links on the advice page

**Comment by neil-ices-dk** [comment]
suggest this ticket can be closed then 🥇
