### ISSUE TITLE
broken image

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/online-advice#31]
![image](https://user-images.githubusercontent.com/23527005/157883520-2733446c-8649-4ff5-9d6e-a6456d519864.png)

should this also have a link to ices.dk?

**Comment by lucalamoni** [comment]
The logo from the internal www directory is not working, if I use a URL as src (the logo from the ices website), then it works. 
So it is partially solved, but not completely

**Comment by lucalamoni** [comment]
new logo (I used a url as a src, because the internal www directory was not working)
link to ices.dk added

**Comment by neil-ices-dk** [comment]
Thanks Luca 😊
