### ISSUE TITLE
empty basket approach

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/online-advice#32]
for a new user, it might not be intutitive what they should do when faced with a blank map, would it be better to default to the first area in the drop down etc. so the user gets a clue how to use the side bars? Especially true as the default landing doesn't even show the map and may be off putting.

![image](https://user-images.githubusercontent.com/23527005/157884648-6d398cf1-e0b2-4fe7-8de4-8dde022099a1.png)

**Comment by lucalamoni** [comment]
I added an initial pop-up with animation to indicate to the user where to start filtering the data. This could be an approach. But it does not cover the side filtering table. Still need some work on this to make it easier to understand.

**Comment by lucalamoni** [comment]
there is a pre-selection now for greater north sea
