### ISSUE TITLE
linking data filtering and stock selection

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/online-advice#33]
Visually, data filtering and stock selection need to be tied together (i.e. greying out stock selection until data filtering is filled etc.) - to make it clear that stock selection is subservient to data filtering. Otherwise, a user may jump straight to stock selection and wonder why there are no stocks

![image](https://user-images.githubusercontent.com/23527005/157886600-3dabcd31-835c-4999-a8c1-8af199a93618.png)

**Comment by lucalamoni** [comment]
It is working only if the ecoregion is selected from the map, not if it is selected from the table. Still need some fixing and refactoring in external JS file

**Comment by neil-ices-dk** [comment]
> It is working only if the ecoregion is selected from the map, not if it is selected from the table. Still need some fixing and refactoring in external JS file

that's an improvement, thanks Luca

**Comment by lucalamoni** [comment]
fixed
