### ISSUE TITLE
Hypertext for labels in Stock Selection

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/online-advice#52]
Stock code i.e. had27.46a20 could be hypertext'd and have a URL to [//vocab.ices.dk/?CodeID=169108](https://vocab.ices.dk/?CodeID=169108)

Stock category (is data category the wrong label?) could link for each value to [//vocab.ices.dk/?ref=1423](https://vocab.ices.dk/?ref=1423)

Advice category; is this the same as CatchScenarioBasis? if, could hypertext each label with the link to the label description [https://vocab.ices.dk/?ref=1570](https://vocab.ices.dk/?ref=1570)

**Comment by neil-ices-dk** [comment]
![image](https://user-images.githubusercontent.com/23527005/173588819-4a3ff567-e699-4a98-a323-48f9ffb27cd7.png)
need to think of some friendlier labels for these

**Comment by lucalamoni** [comment]
Hi @neil-ices-dk, at the moment it is not possible to get from the ICESvocab web services either the link to the stock code page ( displayed on the page as "Link to this Code") or the CodeID, which could be used to build the URL manually.
@colinpmillar and I would suggest asking @mehdiabbasi or @HjalteParner to add codeID to the output from the webservice, or create a new webservice to make the codeID findable. Or alternatively, to make the page work via the code KEY rather than codeID.

**Comment by lucalamoni** [comment]
@neil-ices-dk just a clarification re the labels, you are referring to the table headers or the icons used for the links?

**Comment by mehdiabbasi** [comment]
I will implement this in the RECO new release but just for your info, @lucalamoni & @colinpmillar RECO webpage will need to pass both Code & CodeType because Code is unique in each Code Type. That is the reason we used CodeID or CodeTypeID on the current web page

**Comment by lucalamoni** [comment]
Thank you very much @mehdiabbasi!

**Comment by neil-ices-dk** [comment]
> @neil-ices-dk just a clarification re the labels, you are referring to the table headers or the icons used for the links?

icons are fine, the text labels are cryptic ;)

**Comment by lucalamoni** [comment]
Update: I talked with Mehdi and he will address this in the next few weeks.

**Comment by mehdiabbasi** [comment]
@lucalamoni @colinpmillar @neil-ices-dk I implemented this in the RECO, now you can access a code through the url, just pass CodeType & Code [https://vocab.ices.dk/?codetype=ICES_StockCode&code=cod.27.22-24](https://vocab.ices.dk/?codetype=ICES_StockCode&code=cod.27.22-24)
