### ISSUE TITLE
Stock Assessment Trends: Title?

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/online-advice#53]
the view of the trends need a title at the top as there is no clear signpost of the stock apart from the watermark label;

**Comment by neil-ices-dk** [comment]
the same would also apply to the 'Quality of Assessment' charts

**Comment by lucalamoni** [comment]
Added title with stock description, stock code and year of assessement
<img width="1297" alt="Capture" src="https://user-images.githubusercontent.com/32708094/179724563-65b872c0-8b88-4a6a-a39b-aa38dc1ccabd.PNG">
