### ISSUE TITLE
Make clearer the direction in which the user should move between tabs

### ISSUE THREAD

**Issue by lucalamoni** [ices-tools-dev/online-advice#90]
This could be achieved either by:

- displaying clearly the steps in the help interface
- adding arrows (ie directional symbols) to the tabs' titles
- move the navbar vertically on the left

**Comment by lucalamoni** [comment]
@Neilmagi I added a file in the dev folder in the new branch dedicated to the IBC (this is not related though). In this file you'll find a mock shiny app that shows a potential solution that we could employ to guide the user from the stock selection tab to either the Advice tab or the Scenarios tab. We would need to add 2 additional columns to the stock list table (1 for the Advice tab, 1 for the Scenario tab), with buttons or hypertexts that the user can click and be automatically redirected to the respective tab. 
This is just an idea (I think Alex suggested this in the first place), let me know what you think about it.

**Comment by Neilmagi** [comment]
Hi @lucalamoni, sorry I didn't get to look at this before. What is the name of the file?
